server:
  port: 8080
  mode: debug  # debug, release, test

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "password123"
  dbname: "gin_admin"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  signing_key: "my_secret_key"
