server:
  port: 8080
  mode: debug  # debug, release, test

mysql:
  host: "116.204.135.61"
  port: 3306
  username: "gin-app"
  password: "BwMfPasFwSD4Nexy"
  dbname: "gin-app"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  signing_key: "rbIKH4Pq5eLt7raeFkSgD3CcqIuAD8cIotsPjPhzXHu8ck0xFxAUeUf55zqsjJtg"
